import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { REPO_ROOT } from '../src/dataset.js';
import {
  ACCEPTANCE_SUMMARY_PATH,
  writeAcceptanceSummary,
  RegenerationError,
  buildAcceptanceSummary,
  checkAcceptanceSummary,
  parseRouteRegistry,
  parseTraceabilityMatrix,
  stableStringify,
} from '../src/regenerate.js';

/**
 * TRACE-001 — the acceptance artifacts must regenerate byte-identically.
 *
 * "Deterministic" is a claim that is easy to make and easy to break by
 * accident: a `Date.now()`, a `readdirSync` whose order follows inode
 * allocation, a `localeCompare` that reorders under a different `LC_ALL`, a
 * path that resolves relative to the working directory. Each of those produces
 * a generator that is reproducible on the machine that wrote it and nowhere
 * else — which is worse than no generator, because CI then fails for reasons
 * unrelated to the change under review and the check gets disabled.
 *
 * So this suite attacks determinism from four directions: repeated calls, a
 * separate PROCESS, a hostile environment (timezone, locale, working
 * directory), and the source itself. It also proves the negative — that
 * `--check` really does fail on a stale artifact — because a checker that
 * cannot fail is not a check.
 */

/** The tsx the workspace already installs. No network, no download. */
function tsxBinary(): string {
  const candidates = [
    join(REPO_ROOT, 'packages/runner/node_modules/.bin/tsx'),
    join(REPO_ROOT, 'node_modules/.bin/tsx'),
  ];
  const found = candidates.find((path) => existsSync(path));
  // Deliberately not `it.skip`: a determinism suite that quietly stops running
  // its cross-process cases is a suite that reports determinism it never
  // checked.
  if (!found) throw new Error(`No tsx binary found at any of: ${candidates.join(', ')}`);
  return found;
}

const REGENERATE_ENTRY = join(REPO_ROOT, 'packages/runner/src/regenerate.ts');

interface CliResult {
  status: number;
  output: string;
}

/** Run the REAL entry point — the same file, argv and exit path CI runs. */
function runCli(args: string[], env: NodeJS.ProcessEnv = {}, cwd = REPO_ROOT): CliResult {
  try {
    const output = execFileSync(tsxBinary(), [REGENERATE_ENTRY, ...args], {
      cwd,
      encoding: 'utf8',
      env: { ...process.env, ...env },
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    return { status: 0, output };
  } catch (error) {
    const e = error as { status?: number; stdout?: string; stderr?: string };
    return { status: e.status ?? -1, output: `${e.stdout ?? ''}${e.stderr ?? ''}` };
  }
}

describe('the acceptance summary regenerates byte-identically', () => {
  it('binds the methodology hash to the plan bytes, not only its sidecar', () => {
    const summary = JSON.parse(buildAcceptanceSummary()) as {
      methodologyHash: string;
      inputs: Array<{ path: string; sha256: string }>;
    };
    const planPath = 'docs/methodology/CookingBench-methodology-first-master-plan.md';
    const plan = readFileSync(join(REPO_ROOT, planPath), 'utf8');
    const actual = createHash('sha256').update(plan, 'utf8').digest('hex');

    expect(summary.methodologyHash).toBe(actual);
    expect(summary.inputs).toContainEqual({ path: planPath, sha256: actual });
  });

  it('produces identical bytes on repeated generation', () => {
    const first = buildAcceptanceSummary();
    const second = buildAcceptanceSummary();
    expect(second).toBe(first);
    // Not vacuous: a generator that threw and returned '' would satisfy
    // equality. It has to have actually produced the artifact.
    expect(first.length).toBeGreaterThan(500);
    expect(JSON.parse(first)).toMatchObject({ summaryVersion: 1 });
  });

  it('produces identical bytes from a different process, timezone, locale and directory', () => {
    // A second process shares no module state and no cached anything, so
    // matching bytes here rule out the whole class of "deterministic within one
    // run" bugs. The environment is deliberately hostile: Kiritimati is UTC+14
    // (a date-dependent generator lands on a different day), Turkish is the
    // classic case-folding trap for any locale-aware compare, and `/` as the
    // working directory breaks anything resolving relatively.
    //
    // `--print` rather than `--check`: two runs can agree on a VERDICT about
    // the committed file while disagreeing about content, so the comparison is
    // of the generated bytes themselves.
    const hostile = runCli(['--print'], { TZ: 'Pacific/Kiritimati', LC_ALL: 'tr_TR.UTF-8', LANG: 'tr_TR.UTF-8' }, '/');
    const plain = runCli(['--print'], { TZ: 'UTC', LC_ALL: 'C', LANG: 'C' });
    expect(hostile.status, `hostile-env run said: ${hostile.output}`).toBe(0);
    expect(plain.status, plain.output).toBe(0);
    expect(hostile.output).toBe(plain.output);
    // And identical to what this process builds, so the cross-process check is
    // anchored to the same generator the other tests exercise.
    expect(hostile.output).toBe(buildAcceptanceSummary());
  });

  it('sorts object keys rather than trusting construction order', () => {
    // The property the committed artifact relies on: two objects with the same
    // content and different insertion order serialise identically. Without it
    // an unrelated edit that reorders a literal would churn the artifact and
    // train reviewers to ignore its diff.
    const a = stableStringify({ b: 1, a: { d: [3, 2], c: true } });
    const z = stableStringify({ a: { c: true, d: [3, 2] }, b: 1 });
    expect(a).toBe(z);
    // Array order is content, not presentation, and must NOT be sorted.
    expect(stableStringify([2, 1] as never)).not.toBe(stableStringify([1, 2] as never));
    expect(a.endsWith('\n')).toBe(true);
  });

  it('has no clock, no randomness and no ambient input in the generator source', () => {
    const source = readFileSync(REGENERATE_ENTRY, 'utf8');
    // Stripping comments matters: the module header *discusses* Date.now, and a
    // naive grep would either fail on the prose or be weakened to accommodate
    // it. Neither is acceptable — so the check runs against code only.
    const code = source
      .replace(/\/\*[\s\S]*?\*\//g, '')
      .replace(/^\s*\/\/.*$/gm, '');
    const forbidden: Array<[RegExp, string]> = [
      [/\bDate\.now\s*\(/, 'Date.now() — a timestamp makes every regeneration a diff'],
      [/\bnew Date\s*\(/, 'new Date() — same'],
      [/\bMath\.random\s*\(/, 'Math.random()'],
      [/\bprocess\.env\b/, 'process.env — the output must not depend on the environment'],
      [/\bprocess\.cwd\s*\(/, 'process.cwd() — the output must not depend on the working directory'],
      [/\breaddirSync\b/, 'readdirSync — directory order is not a specification'],
      [/\blocaleCompare\b/, 'localeCompare — reorders under a different LC_ALL'],
      [/\btoLocale[A-Z]/, 'toLocale* — locale-dependent formatting'],
    ];
    for (const [pattern, why] of forbidden) {
      expect(pattern.test(code), `regenerate.ts uses ${why}`).toBe(false);
    }
    // process.argv is permitted, but only on the entry-point line: argv decides
    // --check vs --write, and must never reach the generated bytes.
    const argvLines = code.split('\n').filter((l) => l.includes('process.argv'));
    for (const line of argvLines) {
      expect(line.includes('main(') || line.includes('pathToFileURL')).toBe(true);
    }
  });
});

describe('the regeneration check can actually fail', () => {
  it('leaves the committed summary byte-identical when it is already current', () => {
    // Calls the WRITER, not a helper. The route registry requires a cited test
    // to invoke the route itself; a test of buildAcceptanceSummary proves
    // nothing about the function that puts bytes on disk.
    const before = readFileSync(ACCEPTANCE_SUMMARY_PATH);
    const wrote = writeAcceptanceSummary();
    expect(wrote).toBe(false);
    expect(readFileSync(ACCEPTANCE_SUMMARY_PATH).equals(before)).toBe(true);
  });

  it('reports the committed artifact as up to date', () => {
    const report = checkAcceptanceSummary();
    expect(
      report.ok,
      `${report.detail}\n\n` +
        'docs/wp-0/acceptance-summary.json is DERIVED from docs/wp-0/routes.yaml, ' +
        'docs/wp-0/traceability.yaml and the WP-0 brief. One of them changed without the ' +
        'summary being regenerated. Fix with:\n' +
        '    pnpm --filter @cookingbench/runner exec tsx src/regenerate.ts --write',
    ).toBe(true);
  });

  it('fails, with the offending line, when the committed artifact is stale', () => {
    // The negative case, driven through the real CLI. Everything else in this
    // file would still pass if `--check` returned 0 unconditionally.
    const original = readFileSync(ACCEPTANCE_SUMMARY_PATH, 'utf8');
    try {
      const tampered = original.replace(/"routes": \d+/, '"routes": 9999');
      expect(tampered, 'the tamper did not change anything — the artifact shape moved').not.toBe(original);
      writeFileSync(ACCEPTANCE_SUMMARY_PATH, tampered);
      const result = runCli(['--check']);
      expect(result.status).toBe(1);
      expect(result.output).toContain('is stale at line');
      expect(result.output).toContain('9999');
      expect(result.output).toContain('--write');
    } finally {
      // Restored whatever happened above: a test that leaves a corrupted
      // acceptance artifact behind would fail every later suite for a reason
      // that has nothing to do with the code under review.
      writeFileSync(ACCEPTANCE_SUMMARY_PATH, original);
    }
    expect(readFileSync(ACCEPTANCE_SUMMARY_PATH, 'utf8')).toBe(original);
  });

  it('does not rewrite the artifact when invoked with no arguments', () => {
    // Fail-closed default. If the bare command wrote, then "I ran it to look"
    // and "I changed it" would be the same act, and CI's --check would be
    // self-fulfilling on any machine that had run it once.
    const before = readFileSync(ACCEPTANCE_SUMMARY_PATH, 'utf8');
    const beforeMtime = statSync(ACCEPTANCE_SUMMARY_PATH).mtimeMs;
    runCli([]);
    expect(readFileSync(ACCEPTANCE_SUMMARY_PATH, 'utf8')).toBe(before);
    expect(statSync(ACCEPTANCE_SUMMARY_PATH).mtimeMs).toBe(beforeMtime);
  });

  it('refuses two modes at once rather than picking one', () => {
    for (const args of [['--write', '--check'], ['--write', '--print'], ['--check', '--print']]) {
      const result = runCli(args);
      expect(result.status, `${args.join(' ')} was accepted`).toBe(1);
      expect(result.output).toContain('exactly one');
    }
  });
});

describe('the generator fails closed on an input it cannot read', () => {
  // The failure being designed against: an input file changes shape, the reader
  // silently sees `undefined`, and the summary regenerates cleanly with zero
  // routes. A green build over a broken input is the worst outcome available,
  // so every one of these must throw.

  it('refuses a route registry with no routes', () => {
    expect(() => parseRouteRegistry('routeKinds: [fs-write]\nroutes: []\n')).toThrow(RegenerationError);
    expect(() => parseRouteRegistry('scanRoots: [a]\n')).toThrow(/no `routes` list/);
  });

  it('refuses a route whose kind is outside the declared vocabulary', () => {
    const yaml = [
      'routeKinds: [fs-write]',
      'riskKinds: [historical-overwrite]',
      'severities: [high]',
      'routes:',
      '  - key: x:y:z',
      '    file: packages/runner/src/store.ts',
      '    kind: telepathy',
      '    risks:',
      '      - risk: historical-overwrite',
      '        severity: high',
      '        status: open',
    ].join('\n');
    expect(() => parseRouteRegistry(yaml)).toThrow(/not in the declared routeKinds/);
  });

  it('refuses a registered route that assesses no risk', () => {
    const yaml = [
      'routeKinds: [fs-write]',
      'riskKinds: [historical-overwrite]',
      'severities: [high]',
      'routes:',
      '  - key: x:y:z',
      '    file: packages/runner/src/store.ts',
      '    kind: fs-write',
      '    risks: []',
    ].join('\n');
    expect(() => parseRouteRegistry(yaml)).toThrow(/lists no risks/);
  });

  it('refuses a risk status it cannot count, instead of bucketing it as closed', () => {
    const yaml = [
      'routeKinds: [fs-write]',
      'riskKinds: [historical-overwrite]',
      'severities: [high]',
      'routes:',
      '  - key: x:y:z',
      '    file: packages/runner/src/store.ts',
      '    kind: fs-write',
      '    risks:',
      '      - risk: historical-overwrite',
      '        severity: high',
      '        status: probably-fine',
    ].join('\n');
    expect(() => parseRouteRegistry(yaml)).toThrow(/only 'open' and 'closed' are countable/);
  });

  it('refuses a requirement whose status is not one of the three', () => {
    const yaml = [
      'requirements:',
      '  - id: RUN-001',
      '    status: mostly',
      '    enforcementPoints: []',
      '    tests: []',
      '    gaps: []',
    ].join('\n');
    expect(() => parseTraceabilityMatrix(yaml)).toThrow(/not one of \[closed, partial, open\]/);
  });

  it('refuses a requirement with no id, and a matrix with no requirements', () => {
    expect(() => parseTraceabilityMatrix('requirements:\n  - status: closed\n')).toThrow(/has no id/);
    expect(() => parseTraceabilityMatrix('requirements: []\n')).toThrow(/no `requirements` list/);
  });

  it('refuses a list field that is not a list of strings', () => {
    const yaml = [
      'requirements:',
      '  - id: RUN-001',
      '    status: closed',
      '    enforcementPoints: [ok]',
      '    tests: [{ name: nested }]',
      '    gaps: []',
    ].join('\n');
    expect(() => parseTraceabilityMatrix(yaml)).toThrow(/must be a list of strings/);
  });
});

describe('the summary reports the acceptance state honestly', () => {
  it('derives the requirement list from the brief, not from the matrix', () => {
    const summary = JSON.parse(buildAcceptanceSummary()) as {
      requirements: { declaredInBrief: string[]; documentedInMatrix: string[] };
    };
    const brief = readFileSync(join(REPO_ROOT, 'docs/methodology/WP-0-start-brief.md'), 'utf8');
    const fromBrief = [...brief.matchAll(/^###\s+`([A-Z]+-\d+[A-Z]?)`/gm)].map((m) => m[1]!).sort();
    expect(summary.requirements.declaredInBrief).toEqual(fromBrief);
    // RUN-002 was omitted from the matrix once, and the matrix's own validator
    // did not notice because it took its denominator from the same file.
    expect(summary.requirements.declaredInBrief).toContain('RUN-002');
  });

  it('never claims WP-0 is complete while a requirement is open or a risk is unclosed', () => {
    const summary = JSON.parse(buildAcceptanceSummary()) as {
      acceptance: { wp0Complete: boolean; blockers: string[] };
      requirements: { totals: { closed: number; declared: number } };
      routes: { totals: { openRisks: number; falselyClosedStillOpen: number } };
    };
    const shouldBeComplete =
      summary.requirements.totals.closed === summary.requirements.totals.declared &&
      summary.routes.totals.openRisks === 0 &&
      summary.routes.totals.falselyClosedStillOpen === 0;
    expect(summary.acceptance.wp0Complete).toBe(shouldBeComplete);
    expect(summary.acceptance.blockers.length === 0).toBe(summary.acceptance.wp0Complete);
    if (!shouldBeComplete) {
      // Today: WP-0 is not complete, and the artifact says so in terms. This
      // assertion is here so that flipping the flag requires the underlying
      // work, not an edit to the summary.
      expect(summary.acceptance.wp0Complete).toBe(false);
    }
  });

  it('carries a per-requirement digest, so a reworded gap is still a diff', () => {
    const summary = JSON.parse(buildAcceptanceSummary()) as {
      requirements: { byId: Array<{ id: string; digest: string }> };
    };
    const digests = summary.requirements.byId.map((r) => r.digest);
    expect(new Set(digests).size).toBe(digests.length);
    for (const d of digests) expect(d).toMatch(/^[a-f0-9]{16}$/);
  });
});
